Copilot dev
idriss-xyz/core pull request #187
Opened 2024-12-07 14:48 UTC by MateuszStawski

2024-12-09 12:44 UTC, lennardevertz commented
![image](https://github.com/user-attachments/assets/068bd75c-a7e6-4df5-9e24-fd4bcbc5e0c4)
Is this already using the notification components from @SolutionsEngineer? I see the notifications are not independent elements but contained within some white box

2024-12-09 12:46 UTC, lennardevertz commented
![image](https://github.com/user-attachments/assets/299b75ec-5ae0-47b1-a05f-31f5f893b485)
In this view, add a check if the user is logged in. Compare with what we have in the tipping flow:
![image](https://github.com/user-attachments/assets/80425019-998f-4581-a23d-6234b1945d76)
The button is LOG IN if the user is not logged in, and switches to the actual action `BUY` only then

2024-12-09 13:22 UTC, lennardevertz commented
when I am on this page, github interrups my input in the extension. Try opening the extension's copilot input on this page and start typing `levertz.eth`. by the time you type `l` (small `L`), the label input field on the right side of the PR is focused because l is a shortcut for adding the label

2024-12-09 13:25 UTC, lennardevertz commented
instead of using `id1` for the api calls to the backend (subscription management), ask the user to log in with their wallet and use their wallet as the id

2024-12-12 18:02 UTC, lennardevertz commented
![image](https://github.com/user-attachments/assets/c13c953d-1628-44f3-81cb-f282b2f4b7ef)

Can we use the X icon instead of twitter bird? We have the icon button component in `@idriss-xyz/ui/icon-button` so its unified

2024-12-12 18:10 UTC, lennardevertz commented
![image](https://github.com/user-attachments/assets/3bac562f-dc29-4839-8097-80cd3597329c)
I currently cannot subscribe to an address, only to an ENS

2024-12-12 18:41 UTC, lennardevertz commented
I subscribed to my own address and got the notification in the console that the WSS sent an event, but it didnt display a notification and threw this error:
![image](https://github.com/user-attachments/assets/27e7b55b-61aa-4917-9d83-0a9a76d10256)

2024-12-12 18:46 UTC, lennardevertz commented
![image](https://github.com/user-attachments/assets/ae0b7e29-141c-4a23-9095-b2709280627b)
The user input window showed up with the notification automatically, not through my click on "COPY"

2024-12-12 18:47 UTC, lennardevertz commented
the token that I bought also seems to be hardcoded, use the input from the WSS event

2024-12-13 23:16 UTC, lennardevertz commented
Additionally to allowing users to subscribe to pure wallet addresses and ENS domains, lets also allow Farcaster usernames.
You can resolve those names using

```const FID_URL = `https://fnames.farcaster.xyz/transfers/current?name=${handle}`;
    try {
      const fidResponse = await fetch(FID_URL);
      const fidData = await fidResponse.json();
      if (fidData) {
        userFID = fidData.transfer.to;
      } else {
        return [];
      }
    } catch {
      return [];
    }

    const ADDRESS_URL = `${BASE_API_URL}/snap/get-connected-addresses?fid=${userFID}`;
    const addressResponse = await fetch(ADDRESS_URL);
    const addressData = await addressResponse.json();
    const { result } = addressData;
    if (result?.verifications && result.verifications.length > 0) {
      for (const verification of result.verifications) {
        if (verification.protocol === 'ethereum') {
          connectedAddress = verification.address;
          break;
        }
      }
    }```

2024-12-16 22:20 UTC, lennardevertz commented
![image](https://github.com/user-attachments/assets/8be1e685-7b9b-4fbe-826e-10ed73575183)
Balance still needs rounding as described above

2024-12-16 22:21 UTC, lennardevertz commented
Placeholder change WETH -> ETH

2024-12-16 22:21 UTC, lennardevertz commented
clicking buy errors the extension

2024-12-23 22:51 UTC, lennardevertz requested changes

2024-12-26 10:22 UTC, MateuszStawski commented on apps/extension/src/infrastructure/service-worker/service-worker.ts
> +    this.socket.emit('register', 'id1');
We already changed it. We using id1 only to get test-swaps from api because they're hardcoded to send notification to id1.

2024-12-30 12:17 UTC, lennardevertz approved these changes

2024-12-30 12:50 UTC, merged